### ISSUE TITLE
Add a changelog

### ISSUE THREAD

**Issue by hroncok** [fedora-python/crypt_r#6]
We should add a changelog (to REDAME?). It should say what changes since the fork from CPython and link to CPython 3.12.3 changelog for previous changes.

**Comment by encukou** [comment]
- This library exposes the [crypt_r(3)](https://manpages.debian.org/crypt(3)) function, not [crypt(3)](https://manpages.debian.org/crypt(3)).
  - `crypt_r` is not part of any standard. This library is tested with the `crypt_r` implementation in Fedora ([`libxcrypt`](https://github.com/besser82/libxcrypt), as of 2024), and should work with compatible implementations of `crypt_r` (such as `libcrypt.so` from older `glibc`).
  - Note that the improvements in `crypt_r` over `crypt` are in memory management and thread safety, **not** security/cryptography.

- It is easy to use `crypt_r` in an **insecure** way. Notably:
  - All hashing methods except `METHOD_CRYPT` (the original Unix algorithm from the 1970s) are optional platform-specific extenstions. 
  - This library does not expose modern hashing methods like `libxcrypt`'s `yescrypt`. The last wrapper update is from 2017.

**Comment by hroncok** [comment]
Thanks @encukou. I'll make sure to put that into the README as well.

**Comment by hroncok** [comment]
I opened https://github.com/fedora-python/crypt_r/pull/9 to add the changes mentioned here and to create the changelog section.

I plan to bump the version and add a specific changelog entry for it, once we are ready to release.
